title = "config-file"

[directory]
## settings for the crawling actor to use	
path = ""
last-accessed = ""

[database]
## settings for the database configuration
copies = 1
batch-size = 15

[LLM]
## etc variables here for LLM settings that we can tweak
temp = 1.0

